plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sgggzg.qmzg' // 注意检查这里必须和你的Java包名一致
    compileSdk 35

    defaultConfig {
        applicationId "com.sgggzg.qmzg"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "2.0"

        aaptOptions {
            noCompress "traineddata"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.fragment:fragment:1.8.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'cz.adaptech.tesseract4android:tesseract4android:4.7.0'
    // 加入 Flexbox 依赖
    implementation 'com.google.android.flexbox:flexbox:3.0.0'
}
